### PR TITLE
Support Rtl direction 

### PR DESCRIPTION
**Pull request by hosain-mohamed**
I made a simple change to the padding of the text with icon in the bottom navigation bar so it can support both direction right and left and this would be helpful for languages that supports rtl direction like Arabic. 

the change was simply instead of letting the padding of the text in the button to "only left" it become "symmetric horizontal" and that's it .. I hope this would be accepted as a pull request .

### CODE REVIEW

**Comment by sooxt98** [comment]
LGTM, waiting for more testing

**Comment by hosain-mohamed** [comment]
For more clarification this was the issue before my changes 

Screenshot_1605819238

and this after the changes : 

Screenshot_1605829634

**Comment by sooxt98** [comment]
Ya looks good, but I need some time to review the animation which might
cause unwanted overflow bug

**Comment by hosain-mohamed** [comment]
Any updates 🙂

**Pull request merged**
